# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/connor/Documents/DeepSim/CUDA/TFCPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/connor/Documents/DeepSim/CUDA/TFCPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/connor/Documents/DeepSim/CUDA/TFCPP/CMakeFiles /home/connor/Documents/DeepSim/CUDA/TFCPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/connor/Documents/DeepSim/CUDA/TFCPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_matrix_hold

# Build rule for target.
test_matrix_hold: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_matrix_hold
.PHONY : test_matrix_hold

# fast build rule for target.
test_matrix_hold/fast:
	$(MAKE) -f CMakeFiles/test_matrix_hold.dir/build.make CMakeFiles/test_matrix_hold.dir/build
.PHONY : test_matrix_hold/fast

#=============================================================================
# Target rules for targets named multiply

# Build rule for target.
multiply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiply
.PHONY : multiply

# fast build rule for target.
multiply/fast:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/build
.PHONY : multiply/fast

#=============================================================================
# Target rules for targets named loadmodels_incuda

# Build rule for target.
loadmodels_incuda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loadmodels_incuda
.PHONY : loadmodels_incuda

# fast build rule for target.
loadmodels_incuda/fast:
	$(MAKE) -f CMakeFiles/loadmodels_incuda.dir/build.make CMakeFiles/loadmodels_incuda.dir/build
.PHONY : loadmodels_incuda/fast

#=============================================================================
# Target rules for targets named testmat

# Build rule for target.
testmat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmat
.PHONY : testmat

# fast build rule for target.
testmat/fast:
	$(MAKE) -f CMakeFiles/testmat.dir/build.make CMakeFiles/testmat.dir/build
.PHONY : testmat/fast

#=============================================================================
# Target rules for targets named multigpu

# Build rule for target.
multigpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multigpu
.PHONY : multigpu

# fast build rule for target.
multigpu/fast:
	$(MAKE) -f CMakeFiles/multigpu.dir/build.make CMakeFiles/multigpu.dir/build
.PHONY : multigpu/fast

#=============================================================================
# Target rules for targets named loadmodels

# Build rule for target.
loadmodels: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loadmodels
.PHONY : loadmodels

# fast build rule for target.
loadmodels/fast:
	$(MAKE) -f CMakeFiles/loadmodels.dir/build.make CMakeFiles/loadmodels.dir/build
.PHONY : loadmodels/fast

#=============================================================================
# Target rules for targets named test_tcores

# Build rule for target.
test_tcores: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcores
.PHONY : test_tcores

# fast build rule for target.
test_tcores/fast:
	$(MAKE) -f CMakeFiles/test_tcores.dir/build.make CMakeFiles/test_tcores.dir/build
.PHONY : test_tcores/fast

#=============================================================================
# Target rules for targets named test_copy

# Build rule for target.
test_copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_copy
.PHONY : test_copy

# fast build rule for target.
test_copy/fast:
	$(MAKE) -f CMakeFiles/test_copy.dir/build.make CMakeFiles/test_copy.dir/build
.PHONY : test_copy/fast

#=============================================================================
# Target rules for targets named test_tfvscublas

# Build rule for target.
test_tfvscublas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tfvscublas
.PHONY : test_tfvscublas

# fast build rule for target.
test_tfvscublas/fast:
	$(MAKE) -f CMakeFiles/test_tfvscublas.dir/build.make CMakeFiles/test_tfvscublas.dir/build
.PHONY : test_tfvscublas/fast

src/loadmodels/loadmodels.o: src/loadmodels/loadmodels.cpp.o

.PHONY : src/loadmodels/loadmodels.o

# target to build an object file
src/loadmodels/loadmodels.cpp.o:
	$(MAKE) -f CMakeFiles/loadmodels.dir/build.make CMakeFiles/loadmodels.dir/src/loadmodels/loadmodels.cpp.o
.PHONY : src/loadmodels/loadmodels.cpp.o

src/loadmodels/loadmodels.i: src/loadmodels/loadmodels.cpp.i

.PHONY : src/loadmodels/loadmodels.i

# target to preprocess a source file
src/loadmodels/loadmodels.cpp.i:
	$(MAKE) -f CMakeFiles/loadmodels.dir/build.make CMakeFiles/loadmodels.dir/src/loadmodels/loadmodels.cpp.i
.PHONY : src/loadmodels/loadmodels.cpp.i

src/loadmodels/loadmodels.s: src/loadmodels/loadmodels.cpp.s

.PHONY : src/loadmodels/loadmodels.s

# target to generate assembly for a file
src/loadmodels/loadmodels.cpp.s:
	$(MAKE) -f CMakeFiles/loadmodels.dir/build.make CMakeFiles/loadmodels.dir/src/loadmodels/loadmodels.cpp.s
.PHONY : src/loadmodels/loadmodels.cpp.s

src/loadmodels/loadmodels_incuda.o: src/loadmodels/loadmodels_incuda.cpp.o

.PHONY : src/loadmodels/loadmodels_incuda.o

# target to build an object file
src/loadmodels/loadmodels_incuda.cpp.o:
	$(MAKE) -f CMakeFiles/loadmodels_incuda.dir/build.make CMakeFiles/loadmodels_incuda.dir/src/loadmodels/loadmodels_incuda.cpp.o
.PHONY : src/loadmodels/loadmodels_incuda.cpp.o

src/loadmodels/loadmodels_incuda.i: src/loadmodels/loadmodels_incuda.cpp.i

.PHONY : src/loadmodels/loadmodels_incuda.i

# target to preprocess a source file
src/loadmodels/loadmodels_incuda.cpp.i:
	$(MAKE) -f CMakeFiles/loadmodels_incuda.dir/build.make CMakeFiles/loadmodels_incuda.dir/src/loadmodels/loadmodels_incuda.cpp.i
.PHONY : src/loadmodels/loadmodels_incuda.cpp.i

src/loadmodels/loadmodels_incuda.s: src/loadmodels/loadmodels_incuda.cpp.s

.PHONY : src/loadmodels/loadmodels_incuda.s

# target to generate assembly for a file
src/loadmodels/loadmodels_incuda.cpp.s:
	$(MAKE) -f CMakeFiles/loadmodels_incuda.dir/build.make CMakeFiles/loadmodels_incuda.dir/src/loadmodels/loadmodels_incuda.cpp.s
.PHONY : src/loadmodels/loadmodels_incuda.cpp.s

src/tfcuda/multigpu.o: src/tfcuda/multigpu.cpp.o

.PHONY : src/tfcuda/multigpu.o

# target to build an object file
src/tfcuda/multigpu.cpp.o:
	$(MAKE) -f CMakeFiles/multigpu.dir/build.make CMakeFiles/multigpu.dir/src/tfcuda/multigpu.cpp.o
.PHONY : src/tfcuda/multigpu.cpp.o

src/tfcuda/multigpu.i: src/tfcuda/multigpu.cpp.i

.PHONY : src/tfcuda/multigpu.i

# target to preprocess a source file
src/tfcuda/multigpu.cpp.i:
	$(MAKE) -f CMakeFiles/multigpu.dir/build.make CMakeFiles/multigpu.dir/src/tfcuda/multigpu.cpp.i
.PHONY : src/tfcuda/multigpu.cpp.i

src/tfcuda/multigpu.s: src/tfcuda/multigpu.cpp.s

.PHONY : src/tfcuda/multigpu.s

# target to generate assembly for a file
src/tfcuda/multigpu.cpp.s:
	$(MAKE) -f CMakeFiles/multigpu.dir/build.make CMakeFiles/multigpu.dir/src/tfcuda/multigpu.cpp.s
.PHONY : src/tfcuda/multigpu.cpp.s

src/tfcuda/multiply.o: src/tfcuda/multiply.cu.o

.PHONY : src/tfcuda/multiply.o

# target to build an object file
src/tfcuda/multiply.cu.o:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/src/tfcuda/multiply.cu.o
.PHONY : src/tfcuda/multiply.cu.o

src/tfcuda/multiply.i: src/tfcuda/multiply.cu.i

.PHONY : src/tfcuda/multiply.i

# target to preprocess a source file
src/tfcuda/multiply.cu.i:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/src/tfcuda/multiply.cu.i
.PHONY : src/tfcuda/multiply.cu.i

src/tfcuda/multiply.s: src/tfcuda/multiply.cu.s

.PHONY : src/tfcuda/multiply.s

# target to generate assembly for a file
src/tfcuda/multiply.cu.s:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/src/tfcuda/multiply.cu.s
.PHONY : src/tfcuda/multiply.cu.s

src/tfcuda/test_copy.o: src/tfcuda/test_copy.cpp.o

.PHONY : src/tfcuda/test_copy.o

# target to build an object file
src/tfcuda/test_copy.cpp.o:
	$(MAKE) -f CMakeFiles/test_copy.dir/build.make CMakeFiles/test_copy.dir/src/tfcuda/test_copy.cpp.o
.PHONY : src/tfcuda/test_copy.cpp.o

src/tfcuda/test_copy.i: src/tfcuda/test_copy.cpp.i

.PHONY : src/tfcuda/test_copy.i

# target to preprocess a source file
src/tfcuda/test_copy.cpp.i:
	$(MAKE) -f CMakeFiles/test_copy.dir/build.make CMakeFiles/test_copy.dir/src/tfcuda/test_copy.cpp.i
.PHONY : src/tfcuda/test_copy.cpp.i

src/tfcuda/test_copy.s: src/tfcuda/test_copy.cpp.s

.PHONY : src/tfcuda/test_copy.s

# target to generate assembly for a file
src/tfcuda/test_copy.cpp.s:
	$(MAKE) -f CMakeFiles/test_copy.dir/build.make CMakeFiles/test_copy.dir/src/tfcuda/test_copy.cpp.s
.PHONY : src/tfcuda/test_copy.cpp.s

src/tfcuda/test_matrix_hold.o: src/tfcuda/test_matrix_hold.cpp.o

.PHONY : src/tfcuda/test_matrix_hold.o

# target to build an object file
src/tfcuda/test_matrix_hold.cpp.o:
	$(MAKE) -f CMakeFiles/test_matrix_hold.dir/build.make CMakeFiles/test_matrix_hold.dir/src/tfcuda/test_matrix_hold.cpp.o
.PHONY : src/tfcuda/test_matrix_hold.cpp.o

src/tfcuda/test_matrix_hold.i: src/tfcuda/test_matrix_hold.cpp.i

.PHONY : src/tfcuda/test_matrix_hold.i

# target to preprocess a source file
src/tfcuda/test_matrix_hold.cpp.i:
	$(MAKE) -f CMakeFiles/test_matrix_hold.dir/build.make CMakeFiles/test_matrix_hold.dir/src/tfcuda/test_matrix_hold.cpp.i
.PHONY : src/tfcuda/test_matrix_hold.cpp.i

src/tfcuda/test_matrix_hold.s: src/tfcuda/test_matrix_hold.cpp.s

.PHONY : src/tfcuda/test_matrix_hold.s

# target to generate assembly for a file
src/tfcuda/test_matrix_hold.cpp.s:
	$(MAKE) -f CMakeFiles/test_matrix_hold.dir/build.make CMakeFiles/test_matrix_hold.dir/src/tfcuda/test_matrix_hold.cpp.s
.PHONY : src/tfcuda/test_matrix_hold.cpp.s

src/tfcuda/test_tcores.o: src/tfcuda/test_tcores.cpp.o

.PHONY : src/tfcuda/test_tcores.o

# target to build an object file
src/tfcuda/test_tcores.cpp.o:
	$(MAKE) -f CMakeFiles/test_tcores.dir/build.make CMakeFiles/test_tcores.dir/src/tfcuda/test_tcores.cpp.o
.PHONY : src/tfcuda/test_tcores.cpp.o

src/tfcuda/test_tcores.i: src/tfcuda/test_tcores.cpp.i

.PHONY : src/tfcuda/test_tcores.i

# target to preprocess a source file
src/tfcuda/test_tcores.cpp.i:
	$(MAKE) -f CMakeFiles/test_tcores.dir/build.make CMakeFiles/test_tcores.dir/src/tfcuda/test_tcores.cpp.i
.PHONY : src/tfcuda/test_tcores.cpp.i

src/tfcuda/test_tcores.s: src/tfcuda/test_tcores.cpp.s

.PHONY : src/tfcuda/test_tcores.s

# target to generate assembly for a file
src/tfcuda/test_tcores.cpp.s:
	$(MAKE) -f CMakeFiles/test_tcores.dir/build.make CMakeFiles/test_tcores.dir/src/tfcuda/test_tcores.cpp.s
.PHONY : src/tfcuda/test_tcores.cpp.s

src/tfcuda/test_tfvscublas.o: src/tfcuda/test_tfvscublas.cpp.o

.PHONY : src/tfcuda/test_tfvscublas.o

# target to build an object file
src/tfcuda/test_tfvscublas.cpp.o:
	$(MAKE) -f CMakeFiles/test_tfvscublas.dir/build.make CMakeFiles/test_tfvscublas.dir/src/tfcuda/test_tfvscublas.cpp.o
.PHONY : src/tfcuda/test_tfvscublas.cpp.o

src/tfcuda/test_tfvscublas.i: src/tfcuda/test_tfvscublas.cpp.i

.PHONY : src/tfcuda/test_tfvscublas.i

# target to preprocess a source file
src/tfcuda/test_tfvscublas.cpp.i:
	$(MAKE) -f CMakeFiles/test_tfvscublas.dir/build.make CMakeFiles/test_tfvscublas.dir/src/tfcuda/test_tfvscublas.cpp.i
.PHONY : src/tfcuda/test_tfvscublas.cpp.i

src/tfcuda/test_tfvscublas.s: src/tfcuda/test_tfvscublas.cpp.s

.PHONY : src/tfcuda/test_tfvscublas.s

# target to generate assembly for a file
src/tfcuda/test_tfvscublas.cpp.s:
	$(MAKE) -f CMakeFiles/test_tfvscublas.dir/build.make CMakeFiles/test_tfvscublas.dir/src/tfcuda/test_tfvscublas.cpp.s
.PHONY : src/tfcuda/test_tfvscublas.cpp.s

src/tfcuda/testmat.o: src/tfcuda/testmat.cu.o

.PHONY : src/tfcuda/testmat.o

# target to build an object file
src/tfcuda/testmat.cu.o:
	$(MAKE) -f CMakeFiles/testmat.dir/build.make CMakeFiles/testmat.dir/src/tfcuda/testmat.cu.o
.PHONY : src/tfcuda/testmat.cu.o

src/tfcuda/testmat.i: src/tfcuda/testmat.cu.i

.PHONY : src/tfcuda/testmat.i

# target to preprocess a source file
src/tfcuda/testmat.cu.i:
	$(MAKE) -f CMakeFiles/testmat.dir/build.make CMakeFiles/testmat.dir/src/tfcuda/testmat.cu.i
.PHONY : src/tfcuda/testmat.cu.i

src/tfcuda/testmat.s: src/tfcuda/testmat.cu.s

.PHONY : src/tfcuda/testmat.s

# target to generate assembly for a file
src/tfcuda/testmat.cu.s:
	$(MAKE) -f CMakeFiles/testmat.dir/build.make CMakeFiles/testmat.dir/src/tfcuda/testmat.cu.s
.PHONY : src/tfcuda/testmat.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_matrix_hold"
	@echo "... multiply"
	@echo "... edit_cache"
	@echo "... loadmodels_incuda"
	@echo "... testmat"
	@echo "... multigpu"
	@echo "... loadmodels"
	@echo "... test_tcores"
	@echo "... test_copy"
	@echo "... test_tfvscublas"
	@echo "... src/loadmodels/loadmodels.o"
	@echo "... src/loadmodels/loadmodels.i"
	@echo "... src/loadmodels/loadmodels.s"
	@echo "... src/loadmodels/loadmodels_incuda.o"
	@echo "... src/loadmodels/loadmodels_incuda.i"
	@echo "... src/loadmodels/loadmodels_incuda.s"
	@echo "... src/tfcuda/multigpu.o"
	@echo "... src/tfcuda/multigpu.i"
	@echo "... src/tfcuda/multigpu.s"
	@echo "... src/tfcuda/multiply.o"
	@echo "... src/tfcuda/multiply.i"
	@echo "... src/tfcuda/multiply.s"
	@echo "... src/tfcuda/test_copy.o"
	@echo "... src/tfcuda/test_copy.i"
	@echo "... src/tfcuda/test_copy.s"
	@echo "... src/tfcuda/test_matrix_hold.o"
	@echo "... src/tfcuda/test_matrix_hold.i"
	@echo "... src/tfcuda/test_matrix_hold.s"
	@echo "... src/tfcuda/test_tcores.o"
	@echo "... src/tfcuda/test_tcores.i"
	@echo "... src/tfcuda/test_tcores.s"
	@echo "... src/tfcuda/test_tfvscublas.o"
	@echo "... src/tfcuda/test_tfvscublas.i"
	@echo "... src/tfcuda/test_tfvscublas.s"
	@echo "... src/tfcuda/testmat.o"
	@echo "... src/tfcuda/testmat.i"
	@echo "... src/tfcuda/testmat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

